services:
  twc3sim:
    container_name: twc3sim
    build: https://github.com/lits101/twc3simulator.git#main
    environment:
      - "TASMOTA_IP=10.10.10.10"
    ports:
      - "80:80"
    restart: unless-stopped
